server:
  context-path: /
  port: ${PORT:12345}

spring:
  jpa:
  datasource:
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:eaterdb}?useSSL=false&characterEncoding=UTF-8
    connection-init-sql: 'SELECT 1'